### ISSUE TITLE
Migrate surveilr Roadmap to beautiful individual Astro page

### ISSUE THREAD

**Issue by pradeepcdlm** [surveilr/www.surveilr.com#35]
- [ ] Use timelines, Mermaid gantt chart, or other custom Astro page capabilities to create beautiful easy to read roadmaps for customers. 
  - See https://brycemecum.com/2023/03/31/til-mermaid-tracing/ for ideas 
- [ ] Incorporate the idea of new features in `surveilr` but also new and upcoming _Patterns_ (use cases, industries, disciplines)
- [ ] As new releases and patterns come out, include full blog posts to explain use cases and show utilization patterns
