### ISSUE TITLE
Update surveilr Logos in Default SQLPage App (Shell SQL)

### ISSUE THREAD

**Issue by dittybijil** [surveilr/www.surveilr.com#71]
**Description:**

We need to update the surveilr logos in the default SQLPage app. This involves replacing the current logo references with the correct ones from surveilr's branding. You can point to the following URL `www.surveilr.com/assets/brand/...`

**Tasks:**
- [x]  Move the necessary surveilr brand files to the appropriate directory under `www.surveilr.com/assets/brand/`.
- [x]  Update the default SQLPage app (in shell SQL) to point to the new surveilr logos at the updated URL.
- [x]  Test to ensure the logos are displayed correctly in the app.

**Acceptance Criteria:**
- surveilr logos are correctly displayed in the default SQLPage app.
- All logo references in the app should point to the `www.surveilr.com/assets/brand/...` URL.

**Comment by dittybijil** [comment]
Moved the Surveilr brand files to /www.surveilr.com/assets/brand/, updated the default SQLPage app to use the new logo URLs, and verified correct display.
